# Docker Compose for local Databases
version: "3"

services:
  mysql:
    image: mysql:5.7
    build: ./mysql
    container_name: mysql_host
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: 'Asia/Tokyo'
    volumes:
    - ./docker/db/data:/var/lib/mysql
    - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
    - 3306:3306

  redis:
    # FIXME
    image: redis:3.2
    ports:
      - "6379:6379"
    container_name: redis

  dynamodb:
    image: deangiberson/aws-dynamodb-local
    ports:
      - "8000:8000"
    container_name: dynamodb

  elasticmq:
    image: s12v/elasticmq 
    ports:
      - "9324:9324"
    container_name: elasticmq
    volumes:
      - ./elasticmq/elasticmq.conf:/etc/elasticmq/elasticmq.conf
      
  minio:
    image: minio/minio:RELEASE.2020-06-18T02-23-35Z
    volumes:
      - ./docker/minio/data:/export
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://minio{1...4}/data{1...2}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
      

